version: '3.8'

services:
  # Flask Backend for Testing
  flask-testing:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mingus-flask-testing
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=testing
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///test.db
    volumes:
      - ./backend:/app
      - ./tests:/app/tests
    command: python -m flask run --host=0.0.0.0 --port=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - testing-network

  # React Frontend for Testing
  react-testing:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mingus-react-testing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - CI=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      flask-testing:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - testing-network

  # Chrome Browser for Accessibility Testing
  chrome-testing:
    image: selenium/standalone-chrome:latest
    container_name: mingus-chrome-testing
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC=true
      - SE_VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    networks:
      - testing-network

  # Accessibility Testing Service
  accessibility-tester:
    build:
      context: .
      dockerfile: Dockerfile.testing
    container_name: mingus-accessibility-tester
    environment:
      - FLASK_URL=http://flask-testing:5000
      - REACT_URL=http://react-testing:3000
      - CHROME_URL=http://chrome-testing:4444
      - PYTHONPATH=/app
    volumes:
      - ./tests:/app/tests
      - ./reports:/app/reports
      - ./logs:/app/logs
    depends_on:
      flask-testing:
        condition: service_healthy
      react-testing:
        condition: service_healthy
      chrome-testing:
        condition: service_started
    command: >
      bash -c "
        echo 'Waiting for services to be ready...' &&
        sleep 30 &&
        echo 'Running accessibility tests...' &&
        python -m pytest tests/test_accessibility.py -v --tb=short --html=reports/accessibility-report.html --self-contained-html &&
        echo 'Accessibility testing completed'
      "
    networks:
      - testing-network

  # Test Results Dashboard
  test-dashboard:
    image: nginx:alpine
    container_name: mingus-test-dashboard
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html
      - ./nginx-testing.conf:/etc/nginx/nginx.conf
    depends_on:
      - accessibility-tester
    networks:
      - testing-network

networks:
  testing-network:
    driver: bridge

volumes:
  test-reports:
    driver: local
