"""Reference data for job_postings seed script (#113 Phase A2)."""

from __future__ import annotations

SENIORITY_LEVELS = ("entry", "mid", "senior", "director")

TIER_ROLE_COUNTS = {
    "heavy": {"entry": 3, "mid": 3, "senior": 3, "director": 3},
    "medium": {"entry": 2, "mid": 2, "senior": 2, "director": 2},
    "light": {"entry": 1, "mid": 1, "senior": 1, "director": 1},
}

MSA_CONFIG: dict[str, dict[str, str]] = {
    "35620": {"city": "New York", "state": "NY", "tier": "heavy"},
    "31080": {"city": "Los Angeles", "state": "CA", "tier": "heavy"},
    "16980": {"city": "Chicago", "state": "IL", "tier": "heavy"},
    "19100": {"city": "Dallas", "state": "TX", "tier": "heavy"},
    "41860": {"city": "San Francisco", "state": "CA", "tier": "heavy"},
    "12060": {"city": "Atlanta", "state": "GA", "tier": "medium"},
    "47900": {"city": "Washington", "state": "DC", "tier": "medium"},
    "26420": {"city": "Houston", "state": "TX", "tier": "medium"},
    "38060": {"city": "Phoenix", "state": "AZ", "tier": "medium"},
    "14460": {"city": "Boston", "state": "MA", "tier": "medium"},
    "17460": {"city": "Cleveland", "state": "OH", "tier": "light"},
    "33460": {"city": "Minneapolis", "state": "MN", "tier": "light"},
    "41740": {"city": "San Diego", "state": "CA", "tier": "light"},
    "28140": {"city": "Kansas City", "state": "MO", "tier": "light"},
    "33100": {"city": "Miami", "state": "FL", "tier": "light"},
}

# Strong BLS career fields per CBSA — aligned to local labor market concentration.
MSA_STRONG_FIELDS: dict[str, list[str]] = {
    "35620": [
        "Technology",
        "Finance & Accounting",
        "Legal",
        "Marketing & Communications",
        "Media & Journalism",
        "Creative & Design",
        "Healthcare (Admin/Ops)",
        "Human Resources",
        "Real Estate",
        "Operations & Supply Chain",
        "Sales",
        "Education & Training",
    ],
    "31080": [
        "Technology",
        "Creative & Design",
        "Media & Journalism",
        "Marketing & Communications",
        "Healthcare (Clinical)",
        "Healthcare (Admin/Ops)",
        "Finance & Accounting",
        "Sales",
        "Legal",
        "Operations & Supply Chain",
        "Real Estate",
        "Hospitality & Food Service",
    ],
    "16980": [
        "Finance & Accounting",
        "Operations & Supply Chain",
        "Healthcare (Clinical)",
        "Healthcare (Admin/Ops)",
        "Technology",
        "Legal",
        "Engineering (Civil/Mech/Ind)",
        "Sales",
        "Human Resources",
        "Marketing & Communications",
        "Construction & Trades",
        "Education & Training",
    ],
    "19100": [
        "Technology",
        "Finance & Accounting",
        "Healthcare (Clinical)",
        "Operations & Supply Chain",
        "Sales",
        "Engineering (Civil/Mech/Ind)",
        "Human Resources",
        "Real Estate",
        "Construction & Trades",
        "Legal",
        "Marketing & Communications",
        "Retail & Consumer",
    ],
    "41860": [
        "Technology",
        "Finance & Accounting",
        "Science & Research",
        "Marketing & Communications",
        "Creative & Design",
        "Healthcare (Clinical)",
        "Legal",
        "Operations & Supply Chain",
        "Human Resources",
        "Sales",
        "Engineering (Civil/Mech/Ind)",
        "Real Estate",
    ],
    "12060": [
        "Technology",
        "Finance & Accounting",
        "Healthcare (Clinical)",
        "Healthcare (Admin/Ops)",
        "Operations & Supply Chain",
        "Sales",
        "Marketing & Communications",
        "Human Resources",
    ],
    "47900": [
        "Government & Public Policy",
        "Technology",
        "Finance & Accounting",
        "Legal",
        "Healthcare (Admin/Ops)",
        "Human Resources",
        "Operations & Supply Chain",
        "Marketing & Communications",
    ],
    "26420": [
        "Engineering (Civil/Mech/Ind)",
        "Healthcare (Clinical)",
        "Finance & Accounting",
        "Operations & Supply Chain",
        "Construction & Trades",
        "Sales",
        "Technology",
        "Human Resources",
    ],
    "38060": [
        "Technology",
        "Healthcare (Clinical)",
        "Finance & Accounting",
        "Real Estate",
        "Construction & Trades",
        "Operations & Supply Chain",
        "Sales",
        "Education & Training",
    ],
    "14460": [
        "Technology",
        "Healthcare (Clinical)",
        "Finance & Accounting",
        "Science & Research",
        "Education & Training",
        "Engineering (Civil/Mech/Ind)",
        "Legal",
        "Marketing & Communications",
    ],
    "17460": [
        "Healthcare (Clinical)",
        "Engineering (Civil/Mech/Ind)",
        "Finance & Accounting",
        "Operations & Supply Chain",
    ],
    "33460": [
        "Healthcare (Clinical)",
        "Technology",
        "Finance & Accounting",
        "Operations & Supply Chain",
    ],
    "41740": [
        "Technology",
        "Healthcare (Clinical)",
        "Military / Veterans",
        "Engineering (Civil/Mech/Ind)",
    ],
    "28140": [
        "Finance & Accounting",
        "Healthcare (Admin/Ops)",
        "Operations & Supply Chain",
        "Technology",
    ],
    "33100": [
        "Hospitality & Food Service",
        "Real Estate",
        "Healthcare (Clinical)",
        "Sales",
    ],
}

# 2025-2026 national salary bands (min, max) before MSA cost adjustment.
FIELD_BASE_SALARIES: dict[str, dict[str, tuple[int, int]]] = {
    "Technology": {
        "entry": (72000, 92000),
        "mid": (105000, 135000),
        "senior": (140000, 175000),
        "director": (185000, 260000),
    },
    "Finance & Accounting": {
        "entry": (52000, 68000),
        "mid": (78000, 102000),
        "senior": (108000, 142000),
        "director": (145000, 210000),
    },
    "Healthcare (Clinical)": {
        "entry": (48000, 62000),
        "mid": (68000, 92000),
        "senior": (95000, 125000),
        "director": (120000, 165000),
    },
    "Healthcare (Admin/Ops)": {
        "entry": (45000, 58000),
        "mid": (62000, 82000),
        "senior": (88000, 115000),
        "director": (115000, 155000),
    },
    "Legal": {
        "entry": (58000, 78000),
        "mid": (88000, 118000),
        "senior": (125000, 165000),
        "director": (170000, 240000),
    },
    "Marketing & Communications": {
        "entry": (46000, 60000),
        "mid": (68000, 90000),
        "senior": (95000, 125000),
        "director": (130000, 185000),
    },
    "Sales": {
        "entry": (42000, 58000),
        "mid": (65000, 95000),
        "senior": (95000, 140000),
        "director": (130000, 220000),
    },
    "Education & Training": {
        "entry": (38000, 50000),
        "mid": (52000, 68000),
        "senior": (72000, 95000),
        "director": (95000, 130000),
    },
    "Engineering (Civil/Mech/Ind)": {
        "entry": (62000, 78000),
        "mid": (85000, 108000),
        "senior": (112000, 145000),
        "director": (145000, 195000),
    },
    "Creative & Design": {
        "entry": (44000, 58000),
        "mid": (65000, 88000),
        "senior": (90000, 120000),
        "director": (120000, 170000),
    },
    "Operations & Supply Chain": {
        "entry": (48000, 62000),
        "mid": (68000, 88000),
        "senior": (92000, 118000),
        "director": (120000, 165000),
    },
    "Human Resources": {
        "entry": (44000, 56000),
        "mid": (62000, 82000),
        "senior": (88000, 115000),
        "director": (115000, 160000),
    },
    "Real Estate": {
        "entry": (40000, 55000),
        "mid": (58000, 85000),
        "senior": (85000, 125000),
        "director": (120000, 200000),
    },
    "Social Services & Nonprofit": {
        "entry": (36000, 46000),
        "mid": (48000, 62000),
        "senior": (65000, 85000),
        "director": (85000, 115000),
    },
    "Government & Public Policy": {
        "entry": (45000, 58000),
        "mid": (62000, 82000),
        "senior": (88000, 115000),
        "director": (115000, 155000),
    },
    "Hospitality & Food Service": {
        "entry": (32000, 42000),
        "mid": (45000, 58000),
        "senior": (58000, 78000),
        "director": (78000, 110000),
    },
    "Retail & Consumer": {
        "entry": (34000, 44000),
        "mid": (48000, 62000),
        "senior": (65000, 85000),
        "director": (85000, 120000),
    },
    "Construction & Trades": {
        "entry": (42000, 55000),
        "mid": (58000, 78000),
        "senior": (78000, 105000),
        "director": (105000, 145000),
    },
    "Media & Journalism": {
        "entry": (40000, 52000),
        "mid": (58000, 78000),
        "senior": (82000, 110000),
        "director": (110000, 155000),
    },
    "Science & Research": {
        "entry": (52000, 68000),
        "mid": (72000, 95000),
        "senior": (98000, 130000),
        "director": (135000, 185000),
    },
    "Military / Veterans": {
        "entry": (45000, 58000),
        "mid": (62000, 82000),
        "senior": (85000, 110000),
        "director": (110000, 145000),
    },
    "Self-Employed / Entrepreneurship": {
        "entry": (40000, 65000),
        "mid": (65000, 95000),
        "senior": (95000, 140000),
        "director": (140000, 220000),
    },
}

MSA_SALARY_MULTIPLIERS: dict[str, float] = {
    "35620": 1.38,
    "31080": 1.22,
    "16980": 1.12,
    "19100": 1.06,
    "41860": 1.48,
    "12060": 1.05,
    "47900": 1.28,
    "26420": 1.04,
    "38060": 0.94,
    "14460": 1.22,
    "17460": 0.88,
    "33460": 1.06,
    "41740": 1.14,
    "28140": 0.92,
    "33100": 1.00,
}

FIELD_ROLE_TITLES: dict[str, dict[str, list[str]]] = {
    "Technology": {
        "entry": ["Junior Software Engineer", "Associate Developer", "IT Support Analyst"],
        "mid": ["Software Engineer", "Full-Stack Developer", "DevOps Engineer"],
        "senior": ["Senior Software Engineer", "Staff Engineer", "Senior Data Engineer"],
        "director": ["Engineering Director", "VP of Engineering", "Director of Platform Engineering"],
    },
    "Finance & Accounting": {
        "entry": ["Staff Accountant", "Financial Analyst I", "Accounts Payable Specialist"],
        "mid": ["Senior Financial Analyst", "Accounting Manager", "Corporate Controller"],
        "senior": ["Finance Manager", "Senior Controller", "Treasury Manager"],
        "director": ["Director of Finance", "VP of Finance", "Chief Accounting Officer"],
    },
    "Healthcare (Clinical)": {
        "entry": ["Registered Nurse", "Medical Assistant", "Physical Therapy Aide"],
        "mid": ["Charge Nurse", "Clinical Nurse Specialist", "Physician Assistant"],
        "senior": ["Nurse Practitioner", "Clinical Supervisor", "Lead Therapist"],
        "director": ["Director of Nursing", "Clinical Director", "VP of Patient Care"],
    },
    "Healthcare (Admin/Ops)": {
        "entry": ["Patient Services Coordinator", "Medical Records Clerk", "Scheduling Coordinator"],
        "mid": ["Healthcare Operations Analyst", "Practice Manager", "Revenue Cycle Analyst"],
        "senior": ["Senior Practice Manager", "Healthcare Operations Manager", "Revenue Cycle Manager"],
        "director": ["Director of Operations", "VP of Healthcare Administration", "Chief Operating Officer"],
    },
    "Legal": {
        "entry": ["Paralegal", "Legal Assistant", "Compliance Analyst"],
        "mid": ["Associate Attorney", "Corporate Counsel", "Senior Paralegal"],
        "senior": ["Senior Counsel", "Lead Compliance Officer", "Senior Associate"],
        "director": ["General Counsel", "Director of Legal Affairs", "VP of Compliance"],
    },
    "Marketing & Communications": {
        "entry": ["Marketing Coordinator", "Social Media Specialist", "Communications Assistant"],
        "mid": ["Marketing Manager", "Brand Manager", "Content Strategist"],
        "senior": ["Senior Marketing Manager", "Director of Communications", "Growth Marketing Lead"],
        "director": ["VP of Marketing", "Chief Marketing Officer", "Director of Brand Strategy"],
    },
    "Sales": {
        "entry": ["Sales Development Representative", "Inside Sales Associate", "Account Coordinator"],
        "mid": ["Account Executive", "Regional Sales Manager", "Business Development Manager"],
        "senior": ["Senior Account Executive", "Enterprise Sales Manager", "Sales Team Lead"],
        "director": ["Director of Sales", "VP of Revenue", "Chief Revenue Officer"],
    },
    "Education & Training": {
        "entry": ["Teaching Assistant", "Instructional Aide", "Tutor Coordinator"],
        "mid": ["Classroom Teacher", "Curriculum Specialist", "Training Coordinator"],
        "senior": ["Department Head", "Lead Instructor", "Senior Curriculum Developer"],
        "director": ["Principal", "Director of Curriculum", "VP of Learning & Development"],
    },
    "Engineering (Civil/Mech/Ind)": {
        "entry": ["Junior Civil Engineer", "CAD Technician", "Field Engineer I"],
        "mid": ["Project Engineer", "Mechanical Engineer", "Structural Engineer"],
        "senior": ["Senior Project Engineer", "Lead Mechanical Engineer", "Senior Structural Engineer"],
        "director": ["Engineering Director", "VP of Engineering", "Director of Project Delivery"],
    },
    "Creative & Design": {
        "entry": ["Junior Graphic Designer", "Production Artist", "Design Assistant"],
        "mid": ["UX Designer", "Visual Designer", "Motion Designer"],
        "senior": ["Senior UX Designer", "Lead Product Designer", "Creative Lead"],
        "director": ["Creative Director", "VP of Design", "Director of User Experience"],
    },
    "Operations & Supply Chain": {
        "entry": ["Logistics Coordinator", "Inventory Analyst", "Operations Associate"],
        "mid": ["Supply Chain Analyst", "Operations Manager", "Procurement Specialist"],
        "senior": ["Senior Operations Manager", "Supply Chain Manager", "Distribution Manager"],
        "director": ["Director of Operations", "VP of Supply Chain", "Chief Operations Officer"],
    },
    "Human Resources": {
        "entry": ["HR Coordinator", "Recruiting Coordinator", "Benefits Administrator"],
        "mid": ["HR Business Partner", "Talent Acquisition Manager", "Compensation Analyst"],
        "senior": ["Senior HR Business Partner", "HR Manager", "Lead Recruiter"],
        "director": ["Director of HR", "VP of People", "Chief Human Resources Officer"],
    },
    "Real Estate": {
        "entry": ["Leasing Agent", "Property Coordinator", "Real Estate Assistant"],
        "mid": ["Commercial Real Estate Analyst", "Property Manager", "Real Estate Broker"],
        "senior": ["Senior Property Manager", "Portfolio Manager", "Senior Broker"],
        "director": ["Director of Real Estate", "VP of Asset Management", "Managing Director of Acquisitions"],
    },
    "Government & Public Policy": {
        "entry": ["Policy Analyst I", "Program Assistant", "Legislative Aide"],
        "mid": ["Policy Analyst", "Program Manager", "Regulatory Specialist"],
        "senior": ["Senior Policy Advisor", "Branch Chief", "Senior Program Manager"],
        "director": ["Director of Policy", "Deputy Director", "Chief of Staff"],
    },
    "Hospitality & Food Service": {
        "entry": ["Front Desk Agent", "Line Cook", "Guest Services Associate"],
        "mid": ["Restaurant Manager", "Hotel Operations Manager", "Event Coordinator"],
        "senior": ["General Manager", "Executive Chef", "Senior Event Manager"],
        "director": ["Regional Director of Operations", "Director of Food & Beverage", "VP of Hospitality"],
    },
    "Retail & Consumer": {
        "entry": ["Sales Associate", "Store Supervisor", "Merchandising Assistant"],
        "mid": ["Store Manager", "Category Manager", "District Supervisor"],
        "senior": ["Regional Manager", "Senior Buyer", "Operations Manager"],
        "director": ["Director of Retail Operations", "VP of Merchandising", "Chief Retail Officer"],
    },
    "Construction & Trades": {
        "entry": ["Apprentice Electrician", "Construction Laborer", "HVAC Helper"],
        "mid": ["Journeyman Electrician", "Site Supervisor", "HVAC Technician"],
        "senior": ["Master Electrician", "Construction Superintendent", "Lead HVAC Technician"],
        "director": ["Director of Construction", "VP of Field Operations", "General Superintendent"],
    },
    "Media & Journalism": {
        "entry": ["Production Assistant", "Editorial Assistant", "Digital Content Associate"],
        "mid": ["Reporter", "Producer", "Digital Editor"],
        "senior": ["Senior Producer", "Managing Editor", "Senior Correspondent"],
        "director": ["Executive Producer", "Editor-in-Chief", "Director of Content"],
    },
    "Science & Research": {
        "entry": ["Research Assistant", "Lab Technician", "Clinical Research Coordinator"],
        "mid": ["Research Scientist", "Lab Manager", "Biostatistician"],
        "senior": ["Senior Research Scientist", "Principal Investigator", "Lead Biostatistician"],
        "director": ["Director of Research", "VP of R&D", "Chief Scientific Officer"],
    },
    "Military / Veterans": {
        "entry": ["Veterans Services Coordinator", "Defense Contractor Analyst I", "Logistics Specialist"],
        "mid": ["Program Analyst", "Defense Systems Engineer", "Veterans Outreach Manager"],
        "senior": ["Senior Program Manager", "Lead Systems Analyst", "Senior Veterans Counselor"],
        "director": ["Director of Veterans Programs", "VP of Defense Programs", "Chief of Programs"],
    },
}

FIELD_COMPANIES: dict[str, list[str]] = {
    "Technology": ["Datadog", "MongoDB", "Squarespace", "Bloomberg", "Palantir"],
    "Finance & Accounting": ["BlackRock", "Deloitte", "KPMG", "Goldman Sachs", "Northern Trust"],
    "Healthcare (Clinical)": ["Northwell Health", "HCA Healthcare", "Kaiser Permanente", "Mayo Clinic", "Cleveland Clinic"],
    "Healthcare (Admin/Ops)": ["Optum", "Centene", "Cigna", "Anthem", "Humana"],
    "Legal": ["Kirkland & Ellis", "Latham & Watkins", "Skadden", "DLA Piper", "Sidley Austin"],
    "Marketing & Communications": ["Omnicom", "Publicis", "WPP", "Edelman", "VaynerMedia"],
    "Sales": ["Salesforce", "HubSpot", "Oracle", "SAP", "Adobe"],
    "Education & Training": ["Pearson", "Chegg", "2U", "Coursera", "Kaplan"],
    "Engineering (Civil/Mech/Ind)": ["Bechtel", "Fluor", "AECOM", "Turner Construction", "Jacobs"],
    "Creative & Design": ["Pentagram", "IDEO", "R/GA", "Huge", "Fantasy"],
    "Operations & Supply Chain": ["FedEx", "UPS", "DHL", "XPO Logistics", "Ryder"],
    "Human Resources": ["ADP", "Workday", "Randstad", "ManpowerGroup", "Robert Half"],
    "Real Estate": ["CBRE", "JLL", "Cushman & Wakefield", "Colliers", "Newmark"],
    "Government & Public Policy": ["Deloitte GPS", "Booz Allen", "SAIC", "Leidos", "ICF"],
    "Hospitality & Food Service": ["Marriott", "Hilton", "Darden Restaurants", "Yum! Brands", "Hyatt"],
    "Retail & Consumer": ["Target", "Nordstrom", "Best Buy", "Gap Inc.", "Ulta Beauty"],
    "Construction & Trades": ["Turner Construction", "Whiting-Turner", "Skanska", "Clark Construction", "Gilbane"],
    "Media & Journalism": ["NBCUniversal", "Warner Bros. Discovery", "The New York Times", "Condé Nast", "Hearst"],
    "Science & Research": ["Genentech", "Moderna", "Pfizer", "Broad Institute", "Regeneron"],
    "Military / Veterans": ["General Dynamics", "Lockheed Martin", "Raytheon", "BAE Systems", "Northrop Grumman"],
}

ADVANCEMENT_BY_FIELD: dict[str, dict[str, str]] = {
    "Technology": {
        "entry": "Progress to mid-level engineer owning feature delivery and code reviews within 18-24 months.",
        "mid": "Advance to senior engineer leading architecture decisions and mentoring junior developers.",
        "senior": "Move into staff/principal engineer or engineering management track within 2-3 years.",
        "director": "Potential path to VP Engineering or CTO at growth-stage companies.",
    },
    "Finance & Accounting": {
        "entry": "Eligible for Financial Analyst II or Senior Staff Accountant after 2 years of clean closes.",
        "mid": "Track toward Controller or FP&A Manager with CPA and ERP system ownership.",
        "senior": "Natural progression to Director of Finance or divisional CFO role.",
        "director": "Executive path to CFO or division president at mid-market firms.",
    },
    "Healthcare (Clinical)": {
        "entry": "Advance to charge nurse or specialty certification within 12-18 months.",
        "mid": "Path to nurse practitioner, clinical specialist, or department lead.",
        "senior": "Move into clinical director or advanced practice provider leadership.",
        "director": "Executive track to CNO or system-wide clinical operations leader.",
    },
    "Healthcare (Admin/Ops)": {
        "entry": "Promote to analyst or coordinator lead after mastering revenue cycle workflows.",
        "mid": "Advance to senior practice manager or operations manager overseeing multiple sites.",
        "senior": "Track toward regional operations director or VP of administration.",
        "director": "Executive path to COO of a regional health system.",
    },
    "Legal": {
        "entry": "Advance to senior paralegal or junior associate with bar admission.",
        "mid": "Track toward senior counsel or practice group lead within 3-5 years.",
        "senior": "Natural progression to partner track or general counsel at mid-size firm.",
        "director": "Executive path to GC of a public company or managing partner.",
    },
    "Marketing & Communications": {
        "entry": "Move to marketing specialist or coordinator lead within first year.",
        "mid": "Advance to senior manager owning campaign P&L and team of 3-5.",
        "senior": "Track toward director of marketing or head of brand.",
        "director": "Executive path to CMO or VP of growth at scale-up.",
    },
    "Sales": {
        "entry": "Promote to full-cycle AE after hitting 110% of SDR quota for two quarters.",
        "mid": "Advance to enterprise AE or sales manager leading a pod of 4-6 reps.",
        "senior": "Move into regional sales director or strategic accounts lead.",
        "director": "Executive track to CRO or VP of global sales.",
    },
    "Education & Training": {
        "entry": "Advance to lead teacher or department coordinator after certification.",
        "mid": "Path to department head or instructional coach within 3 years.",
        "senior": "Move into assistant principal or director of curriculum.",
        "director": "Executive track to superintendent or VP of learning.",
    },
    "Engineering (Civil/Mech/Ind)": {
        "entry": "Progress to Engineer-in-Training and project engineer after PE exam prep.",
        "mid": "Advance to senior project engineer managing $5M+ engagements.",
        "senior": "Track toward principal engineer or construction superintendent.",
        "director": "Executive path to VP of engineering or regional director.",
    },
    "Creative & Design": {
        "entry": "Move to mid-level designer owning product surfaces within 12 months.",
        "mid": "Advance to senior designer leading design systems or key product areas.",
        "senior": "Track toward design director or head of product design.",
        "director": "Executive path to VP Design or chief creative officer.",
    },
    "Operations & Supply Chain": {
        "entry": "Promote to analyst II or team lead after optimizing a key process.",
        "mid": "Advance to operations manager overseeing warehouse or fulfillment site.",
        "senior": "Move into regional director of logistics or supply chain.",
        "director": "Executive track to COO or VP of global supply chain.",
    },
    "Human Resources": {
        "entry": "Advance to HR generalist or recruiter II within 18 months.",
        "mid": "Track toward HR manager or senior business partner for a division.",
        "senior": "Move into director of talent or head of people operations.",
        "director": "Executive path to CHRO at growth-stage company.",
    },
    "Real Estate": {
        "entry": "Obtain broker license and move to junior broker within first year.",
        "mid": "Advance to senior broker or portfolio analyst managing $50M+ assets.",
        "senior": "Track toward director of acquisitions or regional asset manager.",
        "director": "Executive path to head of real estate or managing director.",
    },
    "Government & Public Policy": {
        "entry": "Promote to Policy Analyst II or program lead after first legislative cycle.",
        "mid": "Advance to senior advisor or branch chief managing a policy portfolio.",
        "senior": "Track toward director-level appointment or SES candidate.",
        "director": "Executive path to agency deputy director or chief of staff.",
    },
    "Hospitality & Food Service": {
        "entry": "Move to shift supervisor or front desk lead within 6-12 months.",
        "mid": "Advance to assistant general manager or executive sous chef.",
        "senior": "Track toward general manager of flagship property.",
        "director": "Executive path to regional VP of operations.",
    },
    "Retail & Consumer": {
        "entry": "Promote to department lead or key holder within first year.",
        "mid": "Advance to store manager or category lead with P&L ownership.",
        "senior": "Move into district manager overseeing 8-12 locations.",
        "director": "Executive track to VP of retail operations.",
    },
    "Construction & Trades": {
        "entry": "Complete apprenticeship and advance to journeyman within 2-4 years.",
        "mid": "Move to site supervisor or lead technician on commercial projects.",
        "senior": "Track toward superintendent managing multi-phase builds.",
        "director": "Executive path to VP of field operations or general superintendent.",
    },
    "Media & Journalism": {
        "entry": "Advance to staff writer or associate producer after portfolio review.",
        "mid": "Move to senior editor or segment producer owning a beat.",
        "senior": "Track toward managing editor or executive producer.",
        "director": "Executive path to editor-in-chief or head of studio.",
    },
    "Science & Research": {
        "entry": "Progress to research associate or lab lead after protocol mastery.",
        "mid": "Advance to scientist II or project lead on IND-enabling studies.",
        "senior": "Track toward principal investigator or group leader.",
        "director": "Executive path to VP of R&D or CSO at biotech.",
    },
    "Military / Veterans": {
        "entry": "Advance to program analyst II or team lead within federal GS scale.",
        "mid": "Move to senior program manager or lead systems engineer.",
        "senior": "Track toward director of programs or branch chief equivalent.",
        "director": "Executive path to VP of defense programs or SES appointment.",
    },
}
