export type QuizSection = 'emotional' | 'financial' | 'projection';

export type QuestionDef = {
  id: string;
  section: QuizSection;
  title: string;
  hint: string;
  /** emotional: score `value`; financial/projection: score `financial` */
  axis: 'emotional' | 'financial';
  labels: [string, string, string, string];
};

export const VIBE_CHECKUPS_QUESTIONS: QuestionDef[] = [
  {
    id: 'emotional_availability',
    section: 'emotional',
    axis: 'emotional',
    title: 'Emotional availability',
    hint: 'When life gets heavy, how often do you both have space to show up for each other?',
    labels: ['Rarely', 'Sometimes', 'Often', 'Almost always'],
  },
  {
    id: 'conflict_style',
    section: 'emotional',
    axis: 'emotional',
    title: 'Conflict style',
    hint: 'How constructively do disagreements usually get repaired?',
    labels: ['Avoid or blow up', 'Uneven', 'Mostly workable', 'Consistently kind'],
  },
  {
    id: 'shared_values',
    section: 'emotional',
    axis: 'emotional',
    title: 'Shared values',
    hint: 'Alignment on priorities like family, ambition, and lifestyle.',
    labels: ['Mostly unclear', 'Some overlap', 'Mostly aligned', 'Very aligned'],
  },
  {
    id: 'ambition',
    section: 'emotional',
    axis: 'emotional',
    title: 'Ambition & pace',
    hint: 'Career drive, risk tolerance, and how you each define “doing well.”',
    labels: ['Clash hard', 'Often mismatched', 'Mostly in sync', 'We pull for each other'],
  },
  {
    id: 'apology_language',
    section: 'emotional',
    axis: 'emotional',
    title: 'Apologies & accountability',
    hint: 'When someone’s hurt, how reliably does ownership show up?',
    labels: ['Rarely', 'Inconsistent', 'Usually', 'Very reliably'],
  },
  {
    id: 'accountability',
    section: 'emotional',
    axis: 'emotional',
    title: 'Follow-through',
    hint: 'Commitments, chores, and promises — how dependable is the pattern?',
    labels: ['Often dropped', 'Hit or miss', 'Mostly steady', 'Rock solid'],
  },
  {
    id: 'therapy_growth',
    section: 'emotional',
    axis: 'emotional',
    title: 'Growth mindset',
    hint: 'Willingness to learn tools (therapy, books, coaching) when stuck.',
    labels: ['Resistant', 'Skeptical', 'Open sometimes', 'Actively growing'],
  },
  {
    id: 'past_relationship_patterns',
    section: 'emotional',
    axis: 'emotional',
    title: 'Past patterns',
    hint: 'How aware are you both of repeating old dynamics?',
    labels: ['Not aware', 'Somewhat', 'Fairly aware', 'Very intentional'],
  },
  {
    id: 'boundary_setting',
    section: 'emotional',
    axis: 'emotional',
    title: 'Boundaries',
    hint: 'Saying no to family, friends, and work without guilt spirals.',
    labels: ['Very hard', 'Uneven', 'Usually OK', 'Clear & mutual'],
  },
  {
    id: 'time_management',
    section: 'emotional',
    axis: 'emotional',
    title: 'Time & presence',
    hint: 'Between work, friends, and downtime — how much real quality time shows up?',
    labels: ['Rarely enough', 'Uneven', 'Usually balanced', 'We protect it well'],
  },
  {
    id: 'jealousy_insecurity',
    section: 'emotional',
    axis: 'emotional',
    title: 'Jealousy & security',
    hint: 'Trust in friendships, DMs, and independence outside the couple.',
    labels: ['Often tense', 'Sometimes', 'Mostly calm', 'Very secure'],
  },
  {
    id: 'long_term_compatibility',
    section: 'emotional',
    axis: 'emotional',
    title: 'Long-term fit',
    hint: 'Kids, geography, career arcs — how convergent does the vision feel?',
    labels: ['Mostly fuzzy', 'Some overlap', 'Mostly clear', 'Very aligned'],
  },
  {
    id: 'income_transparency',
    section: 'financial',
    axis: 'financial',
    title: 'Income transparency',
    hint: 'How openly do you share numbers, raises, and constraints?',
    labels: ['Hidden', 'Minimal', 'Mostly open', 'Fully transparent'],
  },
  {
    id: 'spending_style',
    section: 'financial',
    axis: 'financial',
    title: 'Spending style',
    hint: 'Impulse vs plan — how often spending feels aligned?',
    labels: ['Chaotic', 'Uneven', 'Mostly planned', 'Very intentional'],
  },
  {
    id: 'debt_situation',
    section: 'financial',
    axis: 'financial',
    title: 'Debt & stress',
    hint: 'How manageable does debt feel as a team?',
    labels: ['Overwhelming', 'Stressful', 'Workable', 'Under control'],
  },
  {
    id: 'savings_habits',
    section: 'financial',
    axis: 'financial',
    title: 'Saving habits',
    hint: 'Emergency fund, goals, and consistency.',
    labels: ['None', 'Sparse', 'Steady', 'Strong'],
  },
  {
    id: 'check_splitting',
    section: 'financial',
    axis: 'financial',
    title: 'Splitting expenses',
    hint: 'Fairness and clarity on who pays for what.',
    labels: ['Often tense', 'Ad hoc', 'Mostly clear', 'Very equitable'],
  },
  {
    id: 'financial_emergency',
    section: 'financial',
    axis: 'financial',
    title: 'Money shocks',
    hint: 'If a $2k surprise hit tomorrow, how would you handle it together?',
    labels: ['Panic', 'Rough', 'Manageable', 'We have a plan'],
  },
  {
    id: 'investment_awareness',
    section: 'financial',
    axis: 'financial',
    title: 'Investing & retirement',
    hint: 'Shared literacy on 401k, index funds, risk, and timelines.',
    labels: ['Avoid topic', 'Confused', 'Learning', 'Aligned strategy'],
  },
  {
    id: 'social_pressure_spending',
    section: 'financial',
    axis: 'financial',
    title: 'Social pressure',
    hint: 'Weddings, trips, gifts — how often FOMO drives spending?',
    labels: ['Constant pull', 'Often', 'Sometimes', 'Rarely'],
  },
  {
    id: 'gift_giving',
    section: 'financial',
    axis: 'financial',
    title: 'Gift-giving expectations',
    hint: 'Holidays, birthdays, and “just because” — how heavy does the spend pressure feel?',
    labels: ['Very heavy', 'Often pricey', 'Manageable', 'Thoughtful & bounded'],
  },
  {
    id: 'housing_situation',
    section: 'financial',
    axis: 'financial',
    title: 'Housing',
    hint: 'Rent vs buy, roommates, family help — how stable does it feel?',
    labels: ['Very unstable', 'Shaky', 'OK', 'Solid'],
  },
  {
    id: 'family_financial_dynamics',
    section: 'financial',
    axis: 'financial',
    title: 'Family money dynamics',
    hint: 'Loans, expectations, and boundaries with parents or relatives.',
    labels: ['Very entangled', 'Stressful', 'Mostly clear', 'Healthy boundaries'],
  },
  {
    id: 'date_expectations',
    section: 'projection',
    axis: 'financial',
    title: 'Date-night expectations',
    hint: 'Helps tune your 12-month “relationship spend” projection.',
    labels: ['Low key', 'Moderate', 'Active', 'Big experiences'],
  },
  {
    id: 'lifestyle_inflation',
    section: 'projection',
    axis: 'financial',
    title: 'Lifestyle creep',
    hint: 'When income rises, how fast does spending rise with it?',
    labels: ['Stays flat', 'Slow drift', 'Noticeable', 'Fast upgrade'],
  },
];

/** Five-question subset for Mingus onboarding Quick Vibe (3 emotional + 2 money). */
export const QUICK_ONBOARDING_VIBE_QUESTIONS: QuestionDef[] = [
  VIBE_CHECKUPS_QUESTIONS[0],
  VIBE_CHECKUPS_QUESTIONS[1],
  VIBE_CHECKUPS_QUESTIONS[2],
  VIBE_CHECKUPS_QUESTIONS[10],
  VIBE_CHECKUPS_QUESTIONS[11],
];
