import type { FluencyCueEntry } from './types';

/**
 * Money Fluency cue playbook (#171).
 * Array order = priority (first matching cue wins per domain + tier).
 */
export const FLUENCY_CUES: FluencyCueEntry[] = [
  // ── MOOD — discretionary risk ─────────────────────────────────────────────
  {
    id: 'disc_risk_high_budget',
    triggerField: 'discretionary_risk',
    triggerValue: 'high',
    tier: 'budget',
    domain: 'mood',
    headline: 'Discretionary spending is the category you have the most control over — the things you choose, not the things you owe.',
    body: 'Stress is the most common reason that bucket gets wider without you noticing.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'disc_risk_high_mid',
    triggerField: 'discretionary_risk',
    triggerValue: 'high',
    tier: 'mid_tier',
    domain: 'mood',
    headline: 'Your spending discipline rating has dropped in weeks when you flag a stress trigger.',
    body: 'Here is what that pattern looks like in your data.',
    expandable: true,
    actionLabel: 'See your cash forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'disc_risk_high_pro',
    triggerField: 'discretionary_risk',
    triggerValue: 'high',
    tier: 'professional',
    domain: 'mood',
    headline: 'Every dollar of reactive spending has an alternative use.',
    body: 'Here is what your last 4 weeks of stress-triggered spending would look like compounded over 5 years.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'disc_risk_watch_budget',
    triggerField: 'discretionary_risk',
    triggerValue: 'watch',
    tier: 'budget',
    domain: 'mood',
    headline: 'You were not sure if stress drove a recent purchase.',
    body: 'That uncertainty is worth paying attention to — it often means the connection is there but not yet visible.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'disc_risk_watch_mid',
    triggerField: 'discretionary_risk',
    triggerValue: 'watch',
    tier: 'mid_tier',
    domain: 'mood',
    headline: 'Discretionary risk is on watch — mood and spending may be linked.',
    body: 'Uncertain triggers often become clear in hindsight. Log the purchase amount and the feeling that preceded it; compare against your weekly check-in next Sunday.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'disc_risk_watch_pro',
    triggerField: 'discretionary_risk',
    triggerValue: 'watch',
    tier: 'professional',
    domain: 'mood',
    headline: 'Discretionary risk is in watch territory — pattern may be forming.',
    body: 'Cross-reference this signal with your last two weekly check-ins. If stress scores rise while spending control falls, escalate to a fixed weekly discretionary cap.',
    expandable: true,
    actionLabel: 'Review forecast',
    actionRoute: '/dashboard/forecast',
  },

  // ── MOOD — surplus trajectory ───────────────────────────────────────────
  {
    id: 'surplus_at_risk_budget',
    triggerField: 'surplus_trajectory',
    triggerValue: 'at_risk',
    tier: 'budget',
    domain: 'mood',
    headline: 'Low spending intentionality puts your surplus — money left after bills — at risk.',
    body: 'Surplus is what remains once fixed costs are covered. Reactive spending erodes it before you notice.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'surplus_at_risk_mid',
    triggerField: 'surplus_trajectory',
    triggerValue: 'at_risk',
    tier: 'mid_tier',
    domain: 'mood',
    headline: 'Surplus trajectory is at risk — spending felt mostly reactive this week.',
    body: 'When intentionality scores drop, discretionary outflows usually rise within two weeks. Set one spending guardrail before next payday.',
    expandable: true,
    actionLabel: 'Check cash outlook',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'surplus_at_risk_pro',
    triggerField: 'surplus_trajectory',
    triggerValue: 'at_risk',
    tier: 'professional',
    domain: 'mood',
    headline: 'Surplus trajectory flagged at risk — reactive spending is compressing margin.',
    body: 'Model this week’s discretionary drift against your 30-day forecast. A 5% trim in flexible categories often restores positive surplus without touching fixed bills.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'surplus_positive_budget',
    triggerField: 'surplus_trajectory',
    triggerValue: 'positive',
    tier: 'budget',
    domain: 'mood',
    headline: 'Intentional spending this week supports a positive surplus path.',
    body: 'Surplus grows when planned choices outnumber reactive ones. Keep noting what felt intentional — it reinforces the habit.',
    expandable: false,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'surplus_positive_mid',
    triggerField: 'surplus_trajectory',
    triggerValue: 'positive',
    tier: 'mid_tier',
    domain: 'mood',
    headline: 'Positive surplus trajectory — your spending choices aligned with intent.',
    body: 'This is the mechanics working: mood stable enough to choose, not react. Consider routing part of this week’s surplus to a named goal.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'surplus_positive_pro',
    triggerField: 'surplus_trajectory',
    triggerValue: 'positive',
    tier: 'professional',
    domain: 'mood',
    headline: 'Surplus trajectory is positive — intentionality is protecting margin.',
    body: 'Use this window to pre-allocate next week’s flexible bucket so gains compound rather than drift back to reactive spending.',
    expandable: true,
    actionLabel: 'View forecast',
    actionRoute: '/dashboard/forecast',
  },

  // ── MOOD — stress-spend pattern ───────────────────────────────────────────
  {
    id: 'stress_spend_pattern_budget',
    triggerField: 'stress_spend_pattern_detected',
    triggerValue: true,
    tier: 'budget',
    domain: 'mood',
    headline: 'A stress-spend pattern is showing up across recent weeks.',
    body: 'This means high stress and loose spending discipline appeared together more than once. Patterns matter more than any single purchase.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'stress_spend_pattern_mid',
    triggerField: 'stress_spend_pattern_detected',
    triggerValue: true,
    tier: 'mid_tier',
    domain: 'mood',
    headline: 'A recurring pattern in your check-ins: when your stress level is high, your spending discipline rating drops.',
    body: 'That pattern has appeared in your data. Here is what it looks like across your last 4 weeks.',
    expandable: true,
    actionLabel: 'See cash impact',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'stress_spend_pattern_pro',
    triggerField: 'stress_spend_pattern_detected',
    triggerValue: true,
    tier: 'professional',
    domain: 'mood',
    headline: 'Your stress-spend correlation is measurable.',
    body: 'On high-stress weeks your discretionary bucket averages wider than on low-stress weeks. That is the number the what-if toggle uses to show your optimized state.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },

  // ── BODY ──────────────────────────────────────────────────────────────────
  {
    id: 'body_work_impact_budget',
    triggerField: 'body_work_impact',
    triggerValue: true,
    tier: 'budget',
    domain: 'body',
    headline: 'Your physical health is affecting work — that ties body costs to income.',
    body: 'Body–career link means health dips can reduce earning power or raise out-of-pocket costs. Both hit the same monthly picture.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'body_work_impact_mid',
    triggerField: 'body_work_impact',
    triggerValue: true,
    tier: 'mid_tier',
    domain: 'body',
    headline: 'Low energy affecting your output at work has a compounding cost.',
    body: 'The difference between performing at 70% and 100% over a year shows up in reviews, raises, and visibility.',
    expandable: true,
    actionLabel: 'Review career tools',
    actionRoute: '/dashboard/tools',
  },
  {
    id: 'body_work_impact_pro',
    triggerField: 'body_work_impact',
    triggerValue: true,
    tier: 'professional',
    domain: 'body',
    headline: 'Physical state and career performance are correlated in your check-in data.',
    body: 'Here is your body score trend alongside your self-reported work impact over the last 8 weeks.',
    expandable: true,
    actionLabel: 'Open tools',
    actionRoute: '/dashboard/tools',
  },
  {
    id: 'body_health_cost_budget',
    triggerField: 'body_ongoing_health_cost',
    triggerValue: true,
    tier: 'budget',
    domain: 'body',
    headline: 'Managing ongoing health costs — medication, therapy, treatment — is a real financial category.',
    body: 'Tracking it makes it visible. Visible costs can be planned for. Invisible costs surprise you.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'body_health_cost_mid',
    triggerField: 'body_ongoing_health_cost',
    triggerValue: true,
    tier: 'mid_tier',
    domain: 'body',
    headline: 'Ongoing health costs are raising your fixed-bills baseline.',
    body: 'When health spend is recurring, it belongs in the fixed layer of your waterfall — not discretionary. Account for it before setting flexible targets.',
    expandable: true,
    actionLabel: 'See forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'body_health_cost_pro',
    triggerField: 'body_ongoing_health_cost',
    triggerValue: true,
    tier: 'professional',
    domain: 'body',
    headline: 'Ongoing health spending is an investment with a return.',
    body: 'Prevention costs less than treatment. Here is how your current health spending compares to the estimated cost of the conditions it is managing.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },

  // ── HOUSING ───────────────────────────────────────────────────────────────
  {
    id: 'housing_cost_increased_budget',
    triggerField: 'fixed_bills_pressure',
    triggerValue: 'elevated',
    tier: 'budget',
    domain: 'housing',
    headline: 'Your rent went up.',
    body: 'A shortfall means your estimated expenses exceed your income for that period — your money runs out before the month does. Here is where that increase shows up in your waterfall.',
    expandable: true,
    actionLabel: 'See waterfall',
    actionRoute: '/dashboard/waterfall',
  },
  {
    id: 'fixed_bills_elevated_budget',
    triggerField: 'fixed_bills_pressure',
    triggerValue: 'elevated',
    tier: 'budget',
    domain: 'housing',
    headline: 'Housing pressure is elevating your fixed bills layer.',
    body: 'Fixed bills are costs that repeat every month — rent, utilities, insurance. When housing spikes, less is left for everything else.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'fixed_bills_elevated_mid',
    triggerField: 'fixed_bills_pressure',
    triggerValue: 'elevated',
    tier: 'mid_tier',
    domain: 'housing',
    headline: 'Fixed bills pressure is elevated — housing costs moved the baseline.',
    body: 'Unexpected repairs or rent increases shift the entire monthly waterfall down. Reconcile the new housing number before adjusting discretionary spend.',
    expandable: true,
    actionLabel: 'Check forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'fixed_bills_elevated_pro',
    triggerField: 'fixed_bills_pressure',
    triggerValue: 'elevated',
    tier: 'professional',
    domain: 'housing',
    headline: 'Fixed bills pressure elevated — housing shock absorbed into baseline.',
    body: 'Isolate the housing delta, rerun 90-day cash projection, and identify which flexible categories absorb the compression versus which need explicit cuts.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'lease_renewal_budget',
    triggerField: 'lease_renewal_imminent',
    triggerValue: true,
    tier: 'budget',
    domain: 'housing',
    headline: 'Your renewal window is open.',
    body: 'Rent-to-income ratio above 30% leaves less room for saving, building wealth, or handling surprises. Do you know if your current rent is at market rate?',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'lease_renewal_mid',
    triggerField: 'lease_renewal_imminent',
    triggerValue: true,
    tier: 'mid_tier',
    domain: 'housing',
    headline: 'Your renewal window is open.',
    body: 'At your current income, a $150 monthly rent increase costs you roughly $1,800 per year — and reduces your savings rate by approximately several percentage points.',
    expandable: true,
    actionLabel: 'See forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'lease_renewal_pro',
    triggerField: 'lease_renewal_imminent',
    triggerValue: true,
    tier: 'professional',
    domain: 'housing',
    headline: 'Lease renewal within 90 days — housing decision horizon is active.',
    body: 'Stress-test stay, renegotiate, and relocate scenarios against cash reserves and commute cost. Lock the decision matrix before notice period pressure.',
    expandable: true,
    actionLabel: 'Open forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'down_payment_behind_budget',
    triggerField: 'down_payment_status',
    triggerValue: 'behind',
    tier: 'budget',
    domain: 'housing',
    headline: 'Your housing savings goal is behind where you want it.',
    body: 'Down payment progress is a long fixed-goal — falling behind means future housing costs may arrive before you are funded.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'down_payment_behind_mid',
    triggerField: 'down_payment_status',
    triggerValue: 'behind',
    tier: 'mid_tier',
    domain: 'housing',
    headline: 'Down payment savings are behind target — housing timeline may slip.',
    body: 'Calculate the monthly gap between current savings rate and goal date. A small automatic transfer often closes it without touching daily discretionary spend.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'down_payment_behind_pro',
    triggerField: 'down_payment_status',
    triggerValue: 'behind',
    tier: 'professional',
    domain: 'housing',
    headline: 'Down payment status behind — housing acquisition timeline at risk.',
    body: 'Reconcile goal date, rate environment, and surplus allocation. Redirect a defined percentage from flexible buckets until the monthly gap closes.',
    expandable: true,
    actionLabel: 'View forecast',
    actionRoute: '/dashboard/forecast',
  },
  {
    id: 'down_payment_not_started_budget',
    triggerField: 'down_payment_status',
    triggerValue: 'not_started',
    tier: 'budget',
    domain: 'housing',
    headline: 'Homeownership builds equity — ownership stake in an asset that typically appreciates.',
    body: "Renting builds your landlord's equity instead. The gap between renting and owning compounds over time.",
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'down_payment_not_started_mid',
    triggerField: 'down_payment_status',
    triggerValue: 'not_started',
    tier: 'mid_tier',
    domain: 'housing',
    headline: "At your current savings rate, here is how long it would take to reach a 10% down payment on a home at your area's median price.",
    body: 'A dedicated savings allocation changes that timeline significantly.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'down_payment_on_track_mid',
    triggerField: 'down_payment_status',
    triggerValue: 'on_track',
    tier: 'mid_tier',
    domain: 'housing',
    headline: 'Down payment savings are on track — housing goal is progressing.',
    body: 'Protect the transfer that got you here. On-track status means your fixed-goal layer is working.',
    expandable: false,
    actionLabel: null,
    actionRoute: null,
  },

  // ── VEHICLE ───────────────────────────────────────────────────────────────
  {
    id: 'vehicle_unsure_mid',
    triggerField: 'vehicle_decision',
    triggerValue: 'unsure',
    tier: 'mid_tier',
    domain: 'vehicle',
    headline: 'The true cost of a vehicle is not the payment — it is depreciation plus insurance plus maintenance plus opportunity cost.',
    body: 'Here is what the keep vs. sell decision looks like at your current numbers.',
    expandable: true,
    actionLabel: 'See vehicle costs',
    actionRoute: '/dashboard/tools',
  },
  {
    id: 'vehicle_selling_pro',
    triggerField: 'vehicle_decision',
    triggerValue: 'selling',
    tier: 'professional',
    domain: 'vehicle',
    headline: "Depreciation is steepest in the first three years of a vehicle's life.",
    body: 'Selling at the right point in the depreciation curve can recover $2,000–$5,000 compared to selling 18 months later.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },

  // ── SPIRIT ────────────────────────────────────────────────────────────────
  {
    id: 'spirit_anxious_budget',
    triggerField: 'financially_anxious',
    triggerValue: true,
    tier: 'budget',
    domain: 'spirit',
    headline: 'Financial anxiety often leads to avoidance — not opening the app, skipping the statement, putting off the decision.',
    body: 'Avoidance does not reduce the bill. It delays awareness and compounds the cost of inaction.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'spirit_anxious_mid',
    triggerField: 'financially_anxious',
    triggerValue: true,
    tier: 'mid_tier',
    domain: 'spirit',
    headline: 'Financial anxiety signal is on — spirit and spending may be linked.',
    body: 'When calm practice and money anxiety coexist, check whether avoidance behaviors (skipping balances, delaying bills) showed up this week too.',
    expandable: true,
    actionLabel: 'Spirit & finance',
    actionRoute: '/dashboard/spirit',
  },
  {
    id: 'spirit_anxious_pro',
    triggerField: 'financially_anxious',
    triggerValue: true,
    tier: 'professional',
    domain: 'spirit',
    headline: 'Financial anxiety flagged — non-rational drivers may be moving cash decisions.',
    body: 'Pair this signal with discretionary risk and forecast variance. Anxiety-driven moves often cluster in the same weeks as unplanned outflows.',
    expandable: true,
    actionLabel: 'Open spirit tools',
    actionRoute: '/dashboard/spirit',
  },

  // ── RELATIONSHIPS ─────────────────────────────────────────────────────────
  {
    id: 'rel_direction_watch_budget',
    triggerField: 'relationship_direction_signal',
    triggerValue: 'watch',
    tier: 'budget',
    domain: 'relationships',
    headline: 'Relationship direction is uncertain or declining — watch the money layer too.',
    body: 'Relationship friction often shows up in spending before it shows up in conversation. Awareness is the first literacy step.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'rel_direction_watch_mid',
    triggerField: 'relationship_direction_signal',
    triggerValue: 'watch',
    tier: 'mid_tier',
    domain: 'relationships',
    headline: 'Relationship direction signal is on watch — spending may follow the trend.',
    body: 'Compare relationship spend this week against your stated intention. Misalignment between direction and dollars is a common leak.',
    expandable: true,
    actionLabel: 'View roster',
    actionRoute: '/dashboard/roster',
  },
  {
    id: 'rel_direction_watch_pro',
    triggerField: 'relationship_direction_signal',
    triggerValue: 'watch',
    tier: 'professional',
    domain: 'relationships',
    headline: 'Relationship direction watch — correlate spend trend with connection trend.',
    body: 'Pull the last four check-in directions for your most-tracked person. If spend rose while direction softened, reallocate before the pattern hardens.',
    expandable: true,
    actionLabel: 'Open roster',
    actionRoute: '/dashboard/roster',
  },
  {
    id: 'rel_direction_positive_budget',
    triggerField: 'relationship_direction_signal',
    triggerValue: 'positive',
    tier: 'budget',
    domain: 'relationships',
    headline: 'Your relationship direction looks positive — spending choices can support that.',
    body: 'Positive direction means invest with intention, not guilt. Know what you are willing to spend to nurture the connection.',
    expandable: false,
    actionLabel: null,
    actionRoute: null,
  },
  {
    id: 'rel_direction_positive_mid',
    triggerField: 'relationship_direction_signal',
    triggerValue: 'positive',
    tier: 'mid_tier',
    domain: 'relationships',
    headline: 'Positive relationship direction — align spend with the trend you want.',
    body: 'When direction and cost awareness match, relationship spending becomes planned discretionary — not hidden leakage.',
    expandable: true,
    actionLabel: null,
    actionRoute: null,
  },
];
