#!/usr/bin/env python3
"""
Seed products table with 30 back-to-school sample items (BTS4 MVP).

10 products per retailer (h&m, nordstrom, amazon).
Run:
    python backend/seeds/seed_products.py
"""

from __future__ import annotations

import os
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


# Placeholder image CDN — replace with real retailer assets in V2.
_IMG = "https://placehold.co/400x500/png?text=BTS"


def get_seed_products() -> list[dict]:
    """Return 30 manually curated BTS products."""
    return [
        # ── H&M (10) ──────────────────────────────────────────────
        {
            "sku": "hm_underwear_g_001",
            "retailer": "h&m",
            "category": "underwear",
            "name": "Pack of 5 Girls Briefs",
            "description": "Soft cotton briefs, everyday pack.",
            "price": 12.99,
            "original_price": 14.99,
            "image_url": f"{_IMG}+HM+Briefs",
            "rating": 4.5,
            "review_count": 128,
            "color": "white",
            "url": "https://www.hm.com/us/product/hm_underwear_g_001",
        },
        {
            "sku": "hm_jeans_g_001",
            "retailer": "h&m",
            "category": "jeans",
            "name": "Black Skinny Fit Jeans",
            "description": "Stretch denim skinny jeans for school.",
            "price": 29.99,
            "image_url": f"{_IMG}+HM+Jeans",
            "rating": 4.3,
            "review_count": 256,
            "color": "black",
            "url": "https://www.hm.com/us/product/hm_jeans_g_001",
        },
        {
            "sku": "hm_shirt_short_g_001",
            "retailer": "h&m",
            "category": "shirt_short",
            "name": "Cotton Short-Sleeve Tee",
            "description": "Everyday crew-neck tee.",
            "price": 9.99,
            "image_url": f"{_IMG}+HM+Tee",
            "rating": 4.4,
            "review_count": 412,
            "color": "white",
            "url": "https://www.hm.com/us/product/hm_shirt_short_g_001",
        },
        {
            "sku": "hm_shirt_long_g_001",
            "retailer": "h&m",
            "category": "shirt_long",
            "name": "Long-Sleeve Jersey Top",
            "description": "Soft jersey long sleeve for cooler mornings.",
            "price": 14.99,
            "image_url": f"{_IMG}+HM+LongSleeve",
            "rating": 4.2,
            "review_count": 98,
            "color": "navy",
            "url": "https://www.hm.com/us/product/hm_shirt_long_g_001",
        },
        {
            "sku": "hm_sneakers_g_001",
            "retailer": "h&m",
            "category": "sneakers",
            "name": "Canvas Low-Top Sneakers",
            "description": "Lightweight school sneakers.",
            "price": 24.99,
            "image_url": f"{_IMG}+HM+Sneakers",
            "rating": 4.1,
            "review_count": 187,
            "color": "white",
            "url": "https://www.hm.com/us/product/hm_sneakers_g_001",
        },
        {
            "sku": "hm_backpack_g_001",
            "retailer": "h&m",
            "category": "backpack",
            "name": "Kids Canvas Backpack",
            "description": "Roomy backpack with front pocket.",
            "price": 19.99,
            "image_url": f"{_IMG}+HM+Backpack",
            "rating": 4.0,
            "review_count": 76,
            "color": "black",
            "url": "https://www.hm.com/us/product/hm_backpack_g_001",
        },
        {
            "sku": "hm_socks_g_001",
            "retailer": "h&m",
            "category": "socks",
            "name": "Pack of 7 Ankle Socks",
            "description": "Week-of-school ankle sock pack.",
            "price": 8.99,
            "image_url": f"{_IMG}+HM+Socks",
            "rating": 4.6,
            "review_count": 301,
            "color": "white",
            "url": "https://www.hm.com/us/product/hm_socks_g_001",
        },
        {
            "sku": "hm_hoodie_g_001",
            "retailer": "h&m",
            "category": "hoodie",
            "name": "Fleece Zip Hoodie",
            "description": "Cozy fleece hoodie for after-school.",
            "price": 24.99,
            "original_price": 29.99,
            "image_url": f"{_IMG}+HM+Hoodie",
            "rating": 4.4,
            "review_count": 215,
            "color": "gray",
            "url": "https://www.hm.com/us/product/hm_hoodie_g_001",
        },
        {
            "sku": "hm_polo_g_001",
            "retailer": "h&m",
            "category": "polo",
            "name": "Piqué Polo Shirt",
            "description": "Uniform-friendly polo.",
            "price": 17.99,
            "image_url": f"{_IMG}+HM+Polo",
            "rating": 4.2,
            "review_count": 143,
            "color": "navy",
            "url": "https://www.hm.com/us/product/hm_polo_g_001",
        },
        {
            "sku": "hm_leggings_g_001",
            "retailer": "h&m",
            "category": "leggings",
            "name": "Soft Stretch Leggings",
            "description": "Everyday stretch leggings.",
            "price": 12.99,
            "image_url": f"{_IMG}+HM+Leggings",
            "rating": 4.5,
            "review_count": 268,
            "color": "black",
            "url": "https://www.hm.com/us/product/hm_leggings_g_001",
        },
        # ── Nordstrom (10) ────────────────────────────────────────
        {
            "sku": "ns_underwear_g_001",
            "retailer": "nordstrom",
            "category": "underwear",
            "name": "Organic Cotton Brief 3-Pack",
            "description": "Premium organic cotton briefs.",
            "price": 28.00,
            "image_url": f"{_IMG}+NS+Briefs",
            "rating": 4.7,
            "review_count": 89,
            "color": "white",
            "url": "https://www.nordstrom.com/s/ns_underwear_g_001",
        },
        {
            "sku": "ns_jeans_g_001",
            "retailer": "nordstrom",
            "category": "jeans",
            "name": "Straight-Leg Stretch Jeans",
            "description": "Mid-rise stretch denim.",
            "price": 49.00,
            "original_price": 59.00,
            "image_url": f"{_IMG}+NS+Jeans",
            "rating": 4.6,
            "review_count": 174,
            "color": "blue",
            "url": "https://www.nordstrom.com/s/ns_jeans_g_001",
        },
        {
            "sku": "ns_shirt_short_g_001",
            "retailer": "nordstrom",
            "category": "shirt_short",
            "name": "Supima Cotton Tee",
            "description": "Soft Supima short-sleeve tee.",
            "price": 22.00,
            "image_url": f"{_IMG}+NS+Tee",
            "rating": 4.5,
            "review_count": 132,
            "color": "gray",
            "url": "https://www.nordstrom.com/s/ns_shirt_short_g_001",
        },
        {
            "sku": "ns_shirt_long_g_001",
            "retailer": "nordstrom",
            "category": "shirt_long",
            "name": "Thermal Long-Sleeve Top",
            "description": "Layering thermal for fall.",
            "price": 32.00,
            "image_url": f"{_IMG}+NS+LongSleeve",
            "rating": 4.4,
            "review_count": 67,
            "color": "black",
            "url": "https://www.nordstrom.com/s/ns_shirt_long_g_001",
        },
        {
            "sku": "ns_sneakers_g_001",
            "retailer": "nordstrom",
            "category": "sneakers",
            "name": "Kids Leather Court Sneakers",
            "description": "Durable leather court style.",
            "price": 65.00,
            "image_url": f"{_IMG}+NS+Sneakers",
            "rating": 4.8,
            "review_count": 203,
            "color": "white",
            "url": "https://www.nordstrom.com/s/ns_sneakers_g_001",
        },
        {
            "sku": "ns_backpack_g_001",
            "retailer": "nordstrom",
            "category": "backpack",
            "name": "Heritage Kids Backpack",
            "description": "Padded laptop sleeve backpack.",
            "price": 48.00,
            "image_url": f"{_IMG}+NS+Backpack",
            "rating": 4.5,
            "review_count": 91,
            "color": "navy",
            "url": "https://www.nordstrom.com/s/ns_backpack_g_001",
        },
        {
            "sku": "ns_socks_g_001",
            "retailer": "nordstrom",
            "category": "socks",
            "name": "Merino Blend Crew Socks 3-Pack",
            "description": "Breathable merino blend socks.",
            "price": 24.00,
            "image_url": f"{_IMG}+NS+Socks",
            "rating": 4.6,
            "review_count": 55,
            "color": "gray",
            "url": "https://www.nordstrom.com/s/ns_socks_g_001",
        },
        {
            "sku": "ns_hoodie_g_001",
            "retailer": "nordstrom",
            "category": "hoodie",
            "name": "French Terry Pullover Hoodie",
            "description": "Soft french terry hoodie.",
            "price": 45.00,
            "image_url": f"{_IMG}+NS+Hoodie",
            "rating": 4.7,
            "review_count": 118,
            "color": "navy",
            "url": "https://www.nordstrom.com/s/ns_hoodie_g_001",
        },
        {
            "sku": "ns_polo_g_001",
            "retailer": "nordstrom",
            "category": "polo",
            "name": "Performance Uniform Polo",
            "description": "Wrinkle-resistant school polo.",
            "price": 35.00,
            "image_url": f"{_IMG}+NS+Polo",
            "rating": 4.3,
            "review_count": 84,
            "color": "white",
            "url": "https://www.nordstrom.com/s/ns_polo_g_001",
        },
        {
            "sku": "ns_jeans_g_002",
            "retailer": "nordstrom",
            "category": "jeans",
            "name": "Black Slim Fit Jeans",
            "description": "Dark wash slim jeans.",
            "price": 54.00,
            "image_url": f"{_IMG}+NS+BlackJeans",
            "rating": 4.4,
            "review_count": 96,
            "color": "black",
            "url": "https://www.nordstrom.com/s/ns_jeans_g_002",
        },
        # ── Amazon (10) ───────────────────────────────────────────
        {
            "sku": "amz_underwear_g_001",
            "retailer": "amazon",
            "category": "underwear",
            "name": "Fruit of the Loom Girls Briefs 6-Pack",
            "description": "Value pack cotton briefs.",
            "price": 11.48,
            "image_url": f"{_IMG}+AMZ+Briefs",
            "rating": 4.6,
            "review_count": 4521,
            "color": "assorted",
            "url": "https://www.amazon.com/dp/amz_underwear_g_001",
        },
        {
            "sku": "amz_jeans_g_001",
            "retailer": "amazon",
            "category": "jeans",
            "name": "Amazon Essentials Skinny Jeans",
            "description": "Affordable stretch skinny jeans.",
            "price": 18.90,
            "image_url": f"{_IMG}+AMZ+Jeans",
            "rating": 4.2,
            "review_count": 1890,
            "color": "blue",
            "url": "https://www.amazon.com/dp/amz_jeans_g_001",
        },
        {
            "sku": "amz_shirt_short_g_001",
            "retailer": "amazon",
            "category": "shirt_short",
            "name": "Gildan Kids Cotton Tee 2-Pack",
            "description": "Value 2-pack crew tees.",
            "price": 12.99,
            "image_url": f"{_IMG}+AMZ+Tee",
            "rating": 4.5,
            "review_count": 3201,
            "color": "black",
            "url": "https://www.amazon.com/dp/amz_shirt_short_g_001",
        },
        {
            "sku": "amz_sneakers_g_001",
            "retailer": "amazon",
            "category": "sneakers",
            "name": "Under Armour Grade School Sneakers",
            "description": "Lightweight athletic sneakers.",
            "price": 39.99,
            "original_price": 49.99,
            "image_url": f"{_IMG}+AMZ+Sneakers",
            "rating": 4.4,
            "review_count": 876,
            "color": "black",
            "url": "https://www.amazon.com/dp/amz_sneakers_g_001",
        },
        {
            "sku": "amz_backpack_g_001",
            "retailer": "amazon",
            "category": "backpack",
            "name": "JanSport SuperBreak Backpack",
            "description": "Classic one-compartment backpack.",
            "price": 35.00,
            "image_url": f"{_IMG}+AMZ+Backpack",
            "rating": 4.7,
            "review_count": 12540,
            "color": "black",
            "url": "https://www.amazon.com/dp/amz_backpack_g_001",
        },
        {
            "sku": "amz_socks_g_001",
            "retailer": "amazon",
            "category": "socks",
            "name": "Hanes Boys/Girls Crew Socks 10-Pack",
            "description": "Bulk crew sock pack for school.",
            "price": 14.00,
            "image_url": f"{_IMG}+AMZ+Socks",
            "rating": 4.5,
            "review_count": 2103,
            "color": "white",
            "url": "https://www.amazon.com/dp/amz_socks_g_001",
        },
        {
            "sku": "amz_hoodie_g_001",
            "retailer": "amazon",
            "category": "hoodie",
            "name": "Amazon Essentials Fleece Hoodie",
            "description": "Budget fleece pullover hoodie.",
            "price": 16.70,
            "image_url": f"{_IMG}+AMZ+Hoodie",
            "rating": 4.3,
            "review_count": 1544,
            "color": "gray",
            "url": "https://www.amazon.com/dp/amz_hoodie_g_001",
        },
        {
            "sku": "amz_polo_g_001",
            "retailer": "amazon",
            "category": "polo",
            "name": "Classroom Uniform Polo",
            "description": "School uniform short-sleeve polo.",
            "price": 9.99,
            "image_url": f"{_IMG}+AMZ+Polo",
            "rating": 4.1,
            "review_count": 678,
            "color": "navy",
            "url": "https://www.amazon.com/dp/amz_polo_g_001",
        },
        {
            "sku": "amz_shirt_long_g_001",
            "retailer": "amazon",
            "category": "shirt_long",
            "name": "Champion Long-Sleeve Tee",
            "description": "Durable long-sleeve cotton tee.",
            "price": 14.50,
            "image_url": f"{_IMG}+AMZ+LongSleeve",
            "rating": 4.4,
            "review_count": 992,
            "color": "gray",
            "url": "https://www.amazon.com/dp/amz_shirt_long_g_001",
        },
        {
            "sku": "amz_jeans_g_002",
            "retailer": "amazon",
            "category": "jeans",
            "name": "Levi's Kids 511 Slim Jeans",
            "description": "Classic slim fit kids jeans.",
            "price": 34.99,
            "image_url": f"{_IMG}+AMZ+Levis",
            "rating": 4.6,
            "review_count": 2340,
            "color": "navy",
            "url": "https://www.amazon.com/dp/amz_jeans_g_002",
        },
    ]


def seed_products() -> int:
    """Populate products table. Returns number of newly inserted rows."""
    from backend.services.products_service import ProductsService

    products = get_seed_products()
    inserted = ProductsService.bulk_create_products(products)
    print(f"Seeded {inserted} new products ({len(products)} in seed set)")
    return inserted


if __name__ == "__main__":
    from app import app

    with app.app_context():
        seed_products()
